In [1]:
import pandas as pd
import numpy as np
import glob
from IPython.display import display, HTML

In [2]:
files_list = glob.glob('other_minerals_*_*.csv')
files_list

['other_minerals_2014-15_DOM.csv',
 'other_minerals_2014-15_ME1_Large.csv',
 'other_minerals_2014-15_ME1_Small.csv',
 'other_minerals_2014-15_ME2_JV.csv',
 'other_minerals_2014-15_ME2_Large.csv',
 'other_minerals_2014-15_ME2_Small.csv',
 'other_minerals_2014-15_ME3_Large.csv',
 'other_minerals_2014-15_ME3_Small.csv',
 'other_minerals_2015-16_DOM.csv',
 'other_minerals_2015-16_ME1_Large.csv',
 'other_minerals_2015-16_ME1_Small.csv',
 'other_minerals_2015-16_ME2_JV.csv',
 'other_minerals_2015-16_ME2_Large.csv',
 'other_minerals_2015-16_ME2_Small.csv',
 'other_minerals_2015-16_ME3.csv']

In [3]:
col_names = ['Code/Ref','Company_Name_cl','License_type_cl','Application_date_cl','Award_date_cl', \
             'Expiry_date_cl','Commodity_cl','Area_km2_cl','Area_acre_cl','Location_state_cl', \
             'License_location_cl','License_location_code_1_cl','License_location_code_2_cl']

dataset_2014_15 = pd.DataFrame(columns=col_names)
dataset_2015_16 = pd.DataFrame(columns=col_names)

In [4]:
def me2_match_locations(df):
    lookup_sheet = pd.read_csv('ME2_2014-15_state_locations.csv')
    lookup_sheet.columns = lookup_sheet.columns.str.replace('ï»¿Code/Ref','Code/Ref')
    lookup_sheet = lookup_sheet[['Code/Ref','Location (Region)']]
    df = df.merge(lookup_sheet,on='Code/Ref')
    
    state_col = 'Location (Region)'
    
    df[state_col] = df[state_col].str.replace('State','')
    df[state_col] = df[state_col].str.strip()
    df[state_col] = df[state_col].str.title()
    df.loc[df[state_col]  == 'Taninthayi', state_col] = 'Tanintharyi'
    df.loc[df[state_col]  == 'Kayar', state_col] = 'Kayah'
    df.loc[df[state_col]  == 'Shan (S)', state_col] = 'Shan'
    df.loc[df[state_col]  == 'Mandalay+Shan', state_col] = ''
    
    if "Location_state_cl" not in df.columns:
        df["Location_state_cl"] = np.nan
    
    df["Location_state_cl"] = df["Location_state_cl"].fillna(df[state_col])
    
    return df

In [5]:
for f in files_list:
    df = pd.read_csv(f)
    print("---"+f+"---")
    year = f.split('_')[2]
    department = f.split('_')[3].split('.csv')[0]
    print(df.columns)
    for c in df.columns:
        if ("_cl" not in c and "Code" not in c):
            df.drop(c, axis=1,inplace=True)
    if 'Code / Ref' in df.columns:
        df.rename(columns={"Code / Ref": "Code/Ref"}, inplace=True)
    if 'Company_name_cl' in df.columns:
        df.rename(columns={"Company_name_cl": "Company_Name_cl"}, inplace=True)
    df['Year'] = year
    df['Department'] = department
    
    if department == 'ME2':
        df = me2_match_locations(df)
    
    display(df.head())
    if (year == '2014-15'):
        dataset_2014_15 = dataset_2014_15.append(df, ignore_index=True)
    else:
        dataset_2015_16 = dataset_2015_16.append(df, ignore_index=True)

---other_minerals_2014-15_DOM.csv---
Index([u'Code/Ref', u'Company_Name_cl', u'License_type_cl',
       u'Date of application', u'Date of award', u'Award_date_cl',
       u'Expiry date', u'Expiry_date_cl', u'Commodity', u'Commodity_cl',
       u'Area (Km2)', u'Area_acre_cl', u'Location (Region)',
       u'Location_state_cl', u'License_location_cl',
       u'License_location_code_1_cl', u'location_working 4',
       u'Coordinates of the license area', u'Column 11'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_acre_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,21/1999,Ayeyawaddy Myitphyar Co;Ltd,Large,2009-11-11,2014-11-10,Coal,3840.00,Kachin,Moemouk,Lweje,2014-15,DOM
1,0005/2009,"Electrum Mining Co.,Ltd",Large,2009-12-21,2019-12-20,Iron,9573.24,Kachin,Waimaw,KanTawYan,2014-15,DOM
2,0034/2011,"SanLin International Co.,Ltd",Large,2011-03-25,2021-03-24,Limestone,1100.00,Kachin,Waimaw,KanTawYan,2014-15,DOM
3,18/1999,"No(2)Heavy Industry,Ministry of Industry",Large,1999-06-15,2019-06-14,Limestone,1033.00,Magway,Tayat,pitthalaine village,2014-15,DOM
4,0006/2014,"Pothar Mining Co.,Ltd",Large,2014-10-12,2024-11-11,Coal,45.00,Magway,Minhla,Kantoak,2014-15,DOM

---other_minerals_2014-15_ME1_Large.csv---
Index([u'Code/Ref', u'License holder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of application', u'Application_date_cl',
       u'Date of award', u'Award_date_cl', u'Expiry date', u'Expiry_date_cl',
       u'Commodity', u'Commodity_cl', u'Area (Km2)', u'Area_km2_cl',
       u'Location (Region)', u'Location_state_cl', u'License_location_cl',
       u'License_location_code_1_cl', u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Application_date_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,156/1998-199,May Flower Mining Enterprise Ltd.,Production Sharing (Large Scale),2000-09-01,2010-11-08,2015-10-08,Zinc Ore,130.54,Kayin,MyaWaddy Township,Maw Khae(Waelay),2014-15,ME1
1,0006/2009,"Win Myint Mo Industries Co.,Ltd.",Production Sharing (Large Scale),2008-01-12,2009-12-31,2024-12-30,Lead and Zinc Concentrate,38.41,Shan,Namtu Township,Namtu,2014-15,ME1
2,0009/2010,"Linn Pyae Mining Co.,Ltd.",Production Sharing (Large Scale),2009-08-20,2010-01-05,2020-04-30,Lead Concentrate,10.03,Shan,Naung Cho Township,Dopin Region,2014-15,ME1
3,0012/2010,"Top Ten Star Production Co.,Ltd.",Production Sharing (Large Scale),2010-01-27,2010-01-07,2020-06-30,Lead Concentrate,1.69,Shan,Kalaw Township,Bawsaing Region,2014-15,ME1
4,0001/2014,"GPS Joint Venture Co., Ltd.",Production Sharing (Large Scale),NaN,NaN,NaN,Lead Concentrate,NaN,Shan,Kalaw Township,Bawsaing Region,2014-15,ME1

---other_minerals_2014-15_ME1_Small.csv---
Index([u'Code/Ref', u'License holder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area (Km2)',
       u'Area_km2_cl', u'Location (Region)',
       u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Year,Department
0,0359/2011,"Harbaw Star Mining Co., Ltd. (Aung KyoKyer)",Production Sharing (Small Scale),2014-03-29,2015-03-28,Lead Ore,49.5,2014-15,ME1
1,0142/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2014-06-29,2015-06-29,Lead and Zinc Associated,49.5,2014-15,ME1
2,0143/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2014-06-29,2015-06-29,Lead and Zinc Associated,49.5,2014-15,ME1
3,0144/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2014-06-29,2015-06-29,Lead and Zinc Associated,49.5,2014-15,ME1
4,0215/2011,"Prince Manufacturing Co., Ltd.",Production Sharing (Small Scale),2014-03-18,2015-03-17,Lead and Zinc Ore,49.5,2014-15,ME1

---other_minerals_2014-15_ME2_JV.csv---
Index([u'Code/Ref', u'License holder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'PSC ratio', u'Date of award', u'Award_date_cl',
       u'Expiry date', u'Expiry_date_cl', u'Commodity', u'Commodity_cl',
       u'Area (Km2)', u'Area_km2_cl', u'Location (Region)',
       u'Location_state_cl'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,Year,Department,Location (Region)
0,5/1999\n22/2019,"Myanmar Pongpipat Co.,L td",Production,1999-07-01T00:00:00Z,2019-06-30T00:00:00Z,Tin and Tungsten Mixed Ore,8.54,Tanintharyi,2014-15,ME2,Tanintharyi
1,8/2004,"Silver Bright Co,Lt d",Production,2004-08-12T00:00:00Z,2019-08-11T00:00:00Z,Tin and Tungsten Mixed Ore,11.82,Tanintharyi,2014-15,ME2,Tanintharyi
2,0002/2015,"Mining World Co.,Ltd",Production,2015-01-12T00:00:00Z,2025-02-11T00:00:00Z,Tin and Tungsten Mixed Ore,1.63,Tanintharyi,2014-15,ME2,Tanintharyi
3,2/2002,"A&A, Natural Resources Development Co,Lt d",Production,2002-02-28T00:00:00Z,2017-02-27T00:00:00Z,Tin and Tungsten Mixed Ore,6.69,Tanintharyi,2014-15,ME2,Tanintharyi
4,0001/2010,"Delco Co.,Ltd",Production,2010-01-05T00:00:00Z,2020-01-04T00:00:00Z,Tin and Tungsten Mixed Ore,8.45,Tanintharyi,2014-15,ME2,Tanintharyi

---other_minerals_2014-15_ME2_Large.csv---
Index([u'Code/Ref', u'License hoder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of application', u'Application_date_cl',
       u'Date of award', u'Award_date_cl', u'Expiry date', u'Expiry_date_cl',
       u'Commodity', u'Commodity_cl', u'Area (Arces)', u'Area_acre_cl',
       u'Location (Region)', u'License_location_cl',
       u'Coordinates of the Iicense area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Application_date_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_acre_cl,License_location_cl,Year,Department,Location (Region),Location_state_cl
0,5/1999\n22/2019,"Myanmar Pongpipat Co.,Ltd",Large Scale,1999-07-01,2019-06-30,2019-06-30,Tin and Tungsten Mixed Ore,2110.00,Heinda Mine,2014-15,ME2,Tanintharyi,Tanintharyi
1,8/2004,"Silver Bright Co,Ltd",Large Scale,2004-08-12,2019-08-11,2019-08-11,Tin and Tungsten Mixed Ore,2920.00,Her Myin Gyi Mine,2014-15,ME2,Tanintharyi,Tanintharyi
2,0002/2015,"Mining World Co.,Ltd",Large Scale,2015-01-12,2025-02-11,2025-02-11,Tin and Tungsten Mixed Ore,403.93,Pakaryi-Sintwingi,2014-15,ME2,Tanintharyi,Tanintharyi
3,2/2002,"A&A, Natural Resources Development Co,Ltd",Large Scale,2002-02-28,2017-02-27,2017-02-27,Tin and Tungsten Mixed Ore,1654.00,Ka lon tar Mine,2014-15,ME2,Tanintharyi,Tanintharyi
4,0001/2010,"Delco Co.,Ltd",Large Scale,2010-01-05,2020-01-04,2020-01-04,Tin and Tungsten Mixed Ore,2087.00,Kan Bauk Mine,2014-15,ME2,Tanintharyi,Tanintharyi

---other_minerals_2014-15_ME2_Small.csv---
Index([u'Code/Ref', u'License holder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area  (Km2)',
       u'Area_km2_cl', u'Location  (Region)', u'License_location_cl',
       u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,License_location_cl,Year,Department,Location (Region),Location_state_cl
0,0168/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2015-10-01,Gold,20.0,Mine Khun,2014-15,ME2,Kachin,Kachin
1,0169/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2015-10-01,Gold,20.0,Kaung Yar,2014-15,ME2,Kachin,Kachin
2,0170/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2015-10-01,Gold,20.0,Kaung Yar,2014-15,ME2,Kachin,Kachin
3,0173/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2015-10-01,Gold,20.0,DaLue,2014-15,ME2,Kachin,Kachin
4,0173/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2015-10-01,Gold,20.0,DaLue,2014-15,ME2,Shan,Shan

---other_minerals_2014-15_ME3_Large.csv---
Index([u'Code/Ref', u'License holder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area (Km2)',
       u'Area_km2_cl', u'Location (Region)', u'Location_state_cl',
       u'Location (Township)', u'License_location_cl', u'Location (Detail)',
       u'License_location_code_1_cl', u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,Production 00014/2000,"Triple A Cement International Co., Ltd",Large,2015-04-07,2020-04-06,Coal,0.284,Shan,Hsipaw,Sanlaung,2014-15,ME3
1,Production 0010/2012,"Triple A Cement International Co., Ltd",Large,2012-07-20,2022-07-19,Limestone,1.201,Mandalay,Kyaukse,Lin Noe Taung,2014-15,ME3
2,Production 0042/2011,"Triple A Cement International Co., Ltd",Large,2016-09-05,2017-09-04,Gypsum,0.607,Shan,Hsipaw,Kwin Pyin,2014-15,ME3
3,Production 0004/2015,"Triple A Cement International Co., Ltd",Large,2015-02-11,2025-02-10,Limestone,0.254,Shan,Ywar Ngan,Kanyuttaung,2014-15,ME3
4,Production 0041/2012,"Triple A Cement International Co., Ltd",Large,2012-09-05,2016-09-04,Bauxite,0.144,Mandalay,Kyaukse,Boe Tawgyi,2014-15,ME3

---other_minerals_2014-15_ME3_Small.csv---
Index([u'Code/Ref', u'License holder', u'Company_name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area (Km2)',
       u'Area_km2_cl', u'Location (Region)', u'Location_state_cl',
       u'Location (Township)', u'License_location_cl', u'Location (Detail)',
       u'License_location_code_1_cl', u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,Production 0002/2011,"UE Export Import Co., Ltd",Small,2014-03-31,2019-03-30,Coal,0.200,Shan,Laishao,Sin Taung,2014-15,ME3
1,Production 0020/2013,"Model industry Co., Ltd.",Small,2009-03-01,2015-02-28,Barite,0.200,Mandalay,Kyauk Se,Pyauk In,2014-15,ME3
2,Production 0016/2009,"Sai Long Hein Mining Co., Ltd.",Small,2015-04-09,2016-04-08,Manganese Dioxide,0.200,Shan,Tachileik,Parshian,2014-15,ME3
3,Production 0063/2011,"Sai Long Hein Mining Co., Ltd.",Small,2012-11-09,2015-11-08,Manganese Dioxide,0.200,Shan,Tachileik,Arrye,2014-15,ME3
4,Production 0045/2009,"Nan Ka Naung Mining and Enginering Co., Ltd.",Small,2009-12-19,2016-12-18,Manganese Dioxide,1.001,Tanintharyi,Boatbyin,Parwei Kyaun,2014-15,ME3

---other_minerals_2015-16_DOM.csv---
Index([u'Code/Ref', u'Company_Name_cl', u'License_type_cl', u'Date of award',
       u'Award_date_cl', u'Expiry date', u'Expiry_date_cl', u'Commodity',
       u'Commodity_cl', u'Area (Km2)', u'Area_acre_cl', u'Location (Region)',
       u'Location_state_cl', u'License_location_cl',
       u'License_location_code_1_cl', u'Location_working 4',
       u'Coordinates of the license area', u'Column 10'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_acre_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,0005/2009,"Htoo International Co.,Ltd",Large,2009-01-21,2019-12-20,Iron,38.74240,Kachin,Waing Maw,Kantawyan,2015-16,DOM
1,0021/2015,Chain Yein Taung Mining,Large,2015-01-05,2025-08-04,Marble,0.20032,Kachin,Chipwi,lanyan,2015-16,DOM
2,0023/2015,Chain Yein Taung Mining,Large,2015-01-02,2025-09-01,Marble,0.80130,Kachin,SawLaw,ManBywal,2015-16,DOM
3,0028/2015,San Linn International,Large,2015-01-20,2030-08-19,Iron,0.80130,Kachin,Chipwi,Hpimaw,2015-16,DOM
4,1/2012,Kayar State Mineral Production Limited,Large,2014-01-28,2019-02-27,Tin and Tungsten Associated,28.42570,Kayah,Phar Saung,Maw Chee,2015-16,DOM

---other_minerals_2015-16_ME1_Large.csv---
Index([u'Code/Ref', u'Company_Name_cl', u'Type of License', u'License_type_cl',
       u'Date of award', u'Award_date_cl', u'Expiry date', u'Expiry_date_cl',
       u'Commodity', u'Commodity_cl', u'Area (Km2)', u'Area_km2_cl',
       u'Location (Region)', u'Location_state_cl', u'License_location_cl',
       u'License_location_code_1_cl', u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,156/1998-199,May Flower Mining Enterprise Ltd.,Production Sharing (Large Scale),2010-08-11,2015-08-10,Zinc Ore,338.10,Kayin,MyaWaddy Township,Maw Khae(Waelay),2015-16,ME1
1,0006/2009,"Win Myint Mo Industries Co.,Ltd.",Production Sharing (Large Scale),2019-12-31,2014-12-30,Lead and Zinc concentrates,99.50,Shan,Namtu Township,Namtu,2015-16,ME1
2,0009/2010,"Linn Pyae Mining Co.,Ltd.",Production Sharing (Large Scale),2010-05-01,2020-04-30,Lead Concentrate,2479.33,Shan,Naung Cho Township,Dopin Region,2015-16,ME1
3,0012/2010,"Top Ten Star Production Co.,Ltd.",Production Sharing (Large Scale),2010-07-01,2020-07-30,Lead Concentrate,418.00,Shan,Kalaw Township,Bawsaing Region,2015-16,ME1
4,0121/2011,"Tha Byu Mining Co., Ltd.",Production Sharing (Large Scale),2011-12-12,2016-12-11,Antimony,396.00,Kayin,Kyar Inn Sitegyi Township ThaPhu,NaN,2015-16,ME1

---other_minerals_2015-16_ME1_Small.csv---
Index([u'Code/Ref', u'License holder', u'Company_name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area (Km2)',
       u'Area_km2_cl', u'Location (Region)',
       u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Year,Department
0,0359/2011,"Harbaw Star Mining Co., Ltd. (Aung KyoKyer)",Production Sharing (Small Scale),2015-03-29,2016-03-28,Lead Ore,49.5,2015-16,ME1
1,0142/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2015-07-29,2020-07-28,Lead-Zinc Ore,49.5,2015-16,ME1
2,0143/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2015-07-29,2020-07-28,Lead-Zinc Ore,49.5,2015-16,ME1
3,0144/2008,"Myanmar Apex (Panwa) Mining Co., Ltd.",Production Sharing (Small Scale),2015-07-29,2020-07-28,Lead-Zinc Ore,49.5,2015-16,ME1
4,0215/2011,"Prince Manufacturing Co., Ltd.",Production Sharing (Small Scale),2015-03-18,2016-03-17,Lead-Zinc Ore,49.5,2015-16,ME1

---other_minerals_2015-16_ME2_JV.csv---
Index([u'Code/Ref', u'License holder', u'Company_name_cl', u'Type of License',
       u'License_type_cl', u'PSC ratio', u'Date of award', u'Award_date_cl',
       u'Expiry date', u'Expiry_date_cl', u'Commodity', u'Commodity_cl',
       u'Area (Km2)', u'Area_km2_cl', u'Location (Region)',
       u'Location_state_cl'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,Year,Department,Location (Region)
0,5/1999\n22/2019,"Myanmar Pongpipat Co.,L td",Production,1999-07-01,2019-06-30,Tin and Tungsten Ore,8.54,Tanintharyi,2015-16,ME2,Tanintharyi
1,8/2004,"Silver Bright Co,Lt d",Production,2004-08-12,2019-08-11,Tin and Tungsten Ore,11.82,Tanintharyi,2015-16,ME2,Tanintharyi
2,0002/2015,"Mining World Co.,Ltd",Production,2015-01-12,2025-02-11,Tin and Tungsten Ore,1.63,Tanintharyi,2015-16,ME2,Tanintharyi
3,2/2002,"A&A, Natural Resources Development Co,Lt d",Production,2002-02-28,2017-02-27,Tin and Tungsten Ore,6.69,Tanintharyi,2015-16,ME2,Tanintharyi
4,0001/2010,"Delco Co.,Ltd",Production,2010-01-05,2020-01-04,Tin and Tungsten Ore,8.45,Tanintharyi,2015-16,ME2,Tanintharyi

---other_minerals_2015-16_ME2_Large.csv---
Index([u'Code/Ref', u'License hoder', u'Company_Name_cl', u'Type of License',
       u'License_type_cl', u'Date of application', u'Application_date_cl',
       u'Date of award', u'Award_date_cl', u'Expiry date', u'Expiry_date_cl',
       u'Commodity', u'Commodity_cl', u'Area (Arces)', u'Area_acre_cl',
       u'Location (Region)', u'License_location_cl',
       u'Coordinates of the Iicense area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Application_date_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_acre_cl,License_location_cl,Year,Department,Location (Region),Location_state_cl
0,5/1999\n22/2019,"Myanmar Pongpipat Co., Ltd",Large Scale,1999-07-01,2019-06-30,2019-06-30,Tin and Tungsten Ore,2110.00,Heinda Mine,2015-16,ME2,Tanintharyi,Tanintharyi
1,8/2004,"Silver Bright Co, Ltd",Large Scale,2004-08-12,2019-08-11,2019-08-11,Tin and Tungsten Ore,2920.00,Her Myin Gyi Mine,2015-16,ME2,Tanintharyi,Tanintharyi
2,0002/2015,"Mining World Co.,Ltd",Large Scale,2015-01-12,2025-02-11,2025-02-11,Tin and Tungsten Ore,403.93,Pakaryi-Sintwingi,2015-16,ME2,Tanintharyi,Tanintharyi
3,2/2002,"A&A, Natural Resources Development Co, Ltd",Large Scale,2002-02-28,2017-02-27,2017-02-27,Tin and Tungsten Ore,1654.00,Ka lon tar Mine,2015-16,ME2,Tanintharyi,Tanintharyi
4,0001/2010,"Delco Co.,Ltd",Large Scale,2010-01-05,2020-01-04,2020-01-04,Tin and Tungsten Ore,2087.00,Kan Bauk Mine,2015-16,ME2,Tanintharyi,Tanintharyi

---other_minerals_2015-16_ME2_Small.csv---
Index([u'Code/Ref', u'License holder', u'Company_name_cl', u'Type of License',
       u'License_type_cl', u'Date of award', u'Award_date_cl', u'Expiry date',
       u'Expiry_date_cl', u'Commodity', u'Commodity_cl', u'Area  (Km2)',
       u'Area_km2_cl', u'Location  (Region)', u'License_location_cl',
       u'Coordinates of the license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,License_type_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,License_location_cl,Year,Department,Location (Region),Location_state_cl
0,0168/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2016-10-01,Gold,20.0,Mine Khun,2015-16,ME2,Kachin,Kachin
1,0169/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2016-10-01,Gold,20.0,Kaung Yar,2015-16,ME2,Kachin,Kachin
2,0170/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2016-10-01,Gold,20.0,Kaung Yar,2015-16,ME2,Kachin,Kachin
3,0173/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2016-10-01,Gold,20.0,Dalue,2015-16,ME2,Kachin,Kachin
4,0173/2013,Sea Sun Star Mining Production & Marketing Co....,Small,2013-10-02,2016-10-01,Gold,20.0,Dalue,2015-16,ME2,Shan,Shan

---other_minerals_2015-16_ME3.csv---
Index([u'No.', u'Code / Ref', u'License Holder', u'Company_name_cl',
       u'Type of \nLicense', u'Date of application', u'Date of \naward',
       u'Award_date_cl', u'Expiry Date', u'Expiry_date_cl', u'Commodity',
       u'Commodity_cl', u'Area \n(sq km)', u'Area_km2_cl',
       u'Location State/ \nRegion', u'Location_state_cl',
       u'License_location_cl', u'License_location_code_1_cl',
       u'Coordinates of the\n license area'],
      dtype='object')

,Code/Ref,Company_Name_cl,Award_date_cl,Expiry_date_cl,Commodity_cl,Area_km2_cl,Location_state_cl,License_location_cl,License_location_code_1_cl,Year,Department
0,Production 00014/2000,"Triple A Cement International Co., Ltd",2015-04-07,2020-04-06,Coal,70.23,Shan,Hsipaw,Sanlaung,2015-16,ME3
1,Production 0010/2012,"Triple A Cement International Co., Ltd",2012-07-20,2022-07-19,Limestone,60.00,Mandalay,Kyaukse,Lin Noe Taung,2015-16,ME3
2,Production 0042/2011,"Triple A Cement International Co., Ltd",2016-09-05,2017-09-04,Gypsum,35.80,Shan,Hsipaw,Kwin Pyin,2015-16,ME3
3,Production 0041/2012,"Triple A Cement International Co., Ltd",2012-09-05,2016-09-04,Bauxite,35.80,Mandalay,Kyaukse,Boe Tawgyi,2015-16,ME3
4,Production 0002/2004,"UE Export Import Co., Ltd",2016-01-27,2017-01-26,Coal,49.50,Shan,Hsipaw,Ma Khaw,2015-16,ME3

In [8]:
dataset_2015_16[dataset_2015_16['Department'] == 'ME2']['Location_state_cl'].value_counts()

Mandalay             302
Sagaing              175
Tanintharyi           56
Shan                  53
Kachin                50
Kayah                 10
Mon                    8
Bago                   2
Mandalay and Shan      1
Name: Location_state_cl, dtype: int64

In [ ]:
dataset_2015_16.to_csv('other_minerals_2015-16.csv')
dataset_2014_15.to_csv('other_minerals_2014-15.csv')